-- Convert the catalog/demo seed data from USD to VND at the project's historical
-- development rate of 1 USD = 25,000 VND. Keep this as a forward migration so
-- databases that already applied the original seed migrations are upgraded too.

UPDATE product_variants
SET price = price * 25000,
    updated_at = NOW()
WHERE sku IN (
    'MBP16-SLV-1TB', 'MBP16-SPG-1TB', 'IP15PM-256-NT', 'IP15PM-512-BL',
    'WH1000XM5-BLK', 'WH1000XM5-SLV', 'PS5-SLIM-DISC', 'PS5-SLIM-DIGI'
)
   OR sku LIKE 'DEMO-SKU-%';

-- Preserve coherence for the orders and inventory movements generated by the
-- demo seed migration. User-created/business data is deliberately untouched.
UPDATE order_items oi
SET unit_price = pv.price,
    subtotal = pv.price * oi.quantity
FROM product_variants pv
WHERE oi.variant_id = pv.id
  AND oi.sku LIKE 'DEMO-SKU-%';

UPDATE orders o
SET total_amount = seeded.total_amount,
    updated_at = NOW()
FROM (
    SELECT oi.order_id, SUM(oi.subtotal) AS total_amount
    FROM order_items oi
    WHERE oi.sku LIKE 'DEMO-SKU-%'
    GROUP BY oi.order_id
) seeded
WHERE o.id = seeded.order_id
  AND o.note LIKE 'Demo delivered order %';

UPDATE stock_movement_items smi
SET unit_cost = smi.unit_cost * 25000
FROM stock_movements sm
WHERE smi.movement_id = sm.id
  AND sm.reference_no LIKE 'DEMO-MOV-%';
