-- Add payment fields to orders table
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(30) NOT NULL DEFAULT 'COD',
    ADD COLUMN IF NOT EXISTS payment_status VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
    ADD COLUMN IF NOT EXISTS upfront_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS finance_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00;
