package com.training.marketplace.analytics;

public enum AnalyticsEventType {
    PAGE_VIEW,
    PRODUCT_VIEW,
    SEARCH,
    ADD_TO_WISHLIST,
    ADD_TO_CART,
    BEGIN_CHECKOUT,
    ORDER_CREATED,
    RECOMMENDATION_IMPRESSION,
    RECOMMENDATION_CLICK,
    CHAT_MESSAGE,
    CHAT_PRODUCT_IMPRESSION,
    CHAT_PRODUCT_CLICK,
    CHAT_VOUCHER_CLICK,
    PURCHASE
}
